### ISSUE TITLE
is watcher working?

### ISSUE THREAD

**Issue by pedropcruz** [sampi/node-less-chokidar#1]
Hello @sampi 

Well i want to use this on my react app. and my first question is: this can compile, but can watch? If yes i can explain how i have the hierarchy and try to solve a problem.

thanks! and good pkg :D +1

**Comment by sampi** [comment]
Hey @pedropcruz ,
Sorry for the late reply =/

I made it with Create React App in mind, this is what I have in my `package.json`

```json
"scripts": {
    "start": "npm run build-css && run-p -ncr watch-css start-js",
    "start-js": "react-scripts start",
    
    "build": "run-s -n build-css build-js",
    "build-js": "react-scripts build",
    
    "test": "run-s -n build-css test-js",
    "test-js": "react-scripts test --env=jsdom",
    
    "build-css": "node-less-chokidar src",
    "watch-css": "node-less-chokidar src --watch"
},
"devDependencies": {
    "node-less-chokidar": "^0.1.0",
    "npm-run-all": "^4.0.2"
}
```

If you write `yarn start` after having these lines in your `package.json` then it should build all CSS from the LESS files and then keep watching,
If you write `yarn test` it will build all files and then run the tests,
`yarn build-css` will build all the CSS, `yarn watch-css` will watch for changes in the LESS files and build them when they change.

There's a bug though in the following case:

Let's say you have these files:

* `variables.less` (all variable definitions, no imports)
* `main.less` (imports `variables.less` and uses the values)

If you change `variables.less` it won't rebuild, because it doesn't know about the dependency graph of the files.
The fix is that if you know you're editing one of these files that are imported by other files, just run `yarn build-css` and everything will be fine.

I will probably fix it in the next update and make some documentation as well, right now I just hacked something together for a project I'm working on =)

**Comment by craig1123** [comment]
Hi @sampi,

I put those exact scripts in my package.json and the less files are not building. I am using react-scripts v.1.0.11. Here is my package.json:

```
{
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "dompurify": "0.9.0",
    "draftjs-to-html": "^0.7.4",
    "prop-types": "^15.5.10",
    "react": "^15.6.1",
    "react-addons-css-transition-group": "^15.6.0",
    "react-dom": "^15.6.1",
    "react-infinite-scroller": "^1.0.15",
    "react-redux": "^5.0.6",
    "react-router-dom": "^4.1.2",
    "react-scripts": "1.0.11",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
  },
  "scripts": {
    "build-css": "node-less-chokidar src",
    "watch-css": "node-less-chokidar src --watch",
    "start-js": "react-scripts start",
    "start": "npm run build-css && run-p -ncr watch-css start-js",
    "build": "run-s -n build-css build-js",
    "build-js": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "eslint": "3.19.0",
    "eslint-loader": "^1.9.0",
    "less": "^2.7.2",
    "node-less-chokidar": "^0.1.0",
    "npm-run-all": "^4.0.2",
    "stylelint": "^8.0.0",
    "stylelint-config-standard": "^17.0.0",
    "stylelint-order": "^0.6.0"
  }
}
```

**Comment by sampi** [comment]
Are you getting some error messages or anything?

**Comment by craig1123** [comment]
I got it working, thanks.

**Comment by sampi** [comment]
@craig1123 what was the fix?

**Comment by knob1** [comment]
@sampi any plans on fixing that annoying bug?
I'm working most of the time with my mixin classes. stopping and restarting the development  server is very annoying. But thanks for your work anyway!

**Comment by sampi** [comment]
@knob1 I usually run `yarn build-css` in a different terminal, without restarting CRA itself.

I'm evaluating different graph crawlers for LESS, once I find one that looks and works well, I can implement it and check when to build which files.

I could just do a quick hack in the meantime, and always build all the files. That would kind of defeat the purpose though =(
